name: vad_example
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  vad: ^0.0.7+1
  record: ^6.1.2
  socket_io_client: ^3.1.2
  livekit_client: ^2.5.1
  http: ^1.5.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
